### ISSUE TITLE
Incompatibility: Soul Protection and Death Barter cause backpacks from the Traveler's Backpack mod to duplicate when they revive the player, when the backpack is in a curios slot

### ISSUE THREAD

**Issue by RecyclingTiger** [Infamous-Misadventures/Dungeons-Gear#124]
Both the Soul Protection effect and Death Barter enchantment cause an additional traveler's backpack to drop on the ground when the player drops to 0 health. The player is still wearing a backpack, meaning the items in the backpack are duplicated.

Video:
https://user-images.githubusercontent.com/89662661/131180451-41eb8562-0358-430c-bebb-d6829faef08c.mp4

**Comment by Jackiecrazy** [comment]
Should be fixed in theory by moving death protection higher in the resolution priority. Let me know if the issue persists.
