### ISSUE TITLE
[1.16.5 EFM intigration] Doge mechanics

### ISSUE THREAD

**Issue by Shibva** [Infamous-Misadventures/Dungeons-Gear#147]
So I found that certain enchants work with dodging, and EFM when it has certain specifications met will allow you to either "dash" or "roll" to dodge.

My suggestion: ik of the texture issue with the mods armor in EFM, but I'm not suggesting that I'm suggesting if you can integrate the mods dodge mechanics to be triggered as well (via a config option)

**Comment by Patrigan** [comment]
This seems like it's pretty out there to do, but we'll take a look at how that works.

**Comment by Thelnfamous1** [comment]
1.16.5 is no longer supported.
