### ISSUE TITLE
[Suggestion] Rearrange tool types

### ISSUE THREAD

**Issue by ChromaPIE** [Infamous-Misadventures/Dungeons-Gear#152]
Been playing Dungeon Gear with Inventorio, a mod providing a few more slots in players inventory including five slots accepting items under each tool types: Sword, Pickaxe, Axe, Shovel and Hoe, thus noticed that some of the weapons' tool types seems to be messed up. For example Katanas, Staffs, and quite a few other series of weapons can only be placed in the slot for pickaxes, and they literally harvest stone type blocks just like a pickaxe, but it do has several Sword specified properties, like being unable to break blocks in Creative, only accepting enchantments for Swords, and so on. For those Axes, both Inventorio slots for Pickaxes and Axes accept them, meaning they are actually axes **and**, at the same time, pickaxes.

I'm not sure if those mentioned above was in fact intended, if not, then it really needs an overhaul to make the mod neater and less confusing.

**Comment by Patrigan** [comment]
Which version would this be?

**Comment by ChromaPIE** [comment]
1.16.5-3.1.9-beta, the latest one.

**Comment by Patrigan** [comment]
Hi, can you take another look. If it doesn't work correctly now, I'm afraid we'll have to get in touch with the Inventorio dev.

**Comment by Thelnfamous1** [comment]
Issue has no further elaboration and 1.16.5 is no longer supported.
